name: sharedalbumapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_app_check: any
  firebase_auth: ^5.7.0
  firebase_database: ^11.3.10
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.1.0
  shared_preferences: ^2.2.2
  image: ^4.1.0
  cloud_functions: ^5.6.2       # [병합] 최신 버전 선택
  livekit_client: ^2.5.1        # [병합] 추가
  flutter_webrtc: ^1.2.0        # [병합] 추가
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  photo_manager: ^3.7.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1   # ✅ 여기에 추가

flutter_launcher_icons:
  android: true
  ios: true

  # iOS: 풀블리드 한 장
  image_path_ios: "assets/icons/icon_fullbleed_ios.png"
  remove_alpha_ios: true

  # ✅ Android 쪽은 “기본 경로 1개”가 필요(검증용)
  image_path_android: "assets/icons/icon_fullbleed_ios.png"

  # ✅ 실제 표시될 건 Adaptive 아이콘(전경/배경 분리)
  adaptive_icon_background: "#E9E0F4"
  adaptive_icon_foreground: "assets/icons/icon_fg_android_safe2.png"

dependency_overrides:
  google_sign_in: 6.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/google_logo.png
    - assets/icons/shared_album_list.png
    - assets/mediapipe/face_landmarker.task