name: sharedalbumapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  firebase_database: ^11.3.10
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  google_sign_in: 6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  google_sign_in: 6.1.0

flutter:
  uses-material-design: true