name: sharedalbumapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  firebase_app_check: any
  firebase_auth: ^5.7.0
  firebase_database: ^11.3.10
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.1.0
  shared_preferences: ^2.2.2
  
  cloud_functions: ^5.1.3   # joinVoiceRoom, leaveVoiceRoom 같은 Cloud Functions 호출
  flutter_webrtc: ^0.12.7   # WebRTC(보이스/영상 통화) 핵심 패키지
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:

    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  google_sign_in: 6.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/images/google_logo.png
    - assets/icons/shared_album_list.png
